<a href="https://colab.research.google.com/github/michaeledge27/mathModeling/blob/main/projects/permanentProblem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np

In [30]:
def permRecurse(row, used, mat):
    N = len(mat[0])
    v = 0
    if row == N:
        return 1
    else:
      for j in range(N):
        if (not used[j] and mat[row][j] != 0):
          used[j] = True
          v += permRecurse(row + 1, used, mat)
          used[j] = False
      return v

In [31]:
# def generateRandomMatrix(n, m):
#     return np.random.randint(2, size=(n, m))

In [32]:
# return the number of ones in a given matrix
def onesCount(matrix):
    return np.count_nonzero(matrix)

In [33]:
def generate_matrix():
    # generate 8x8 matrix with all 0's
    matrix = np.zeros((8, 8), dtype=int)
    # randomly select 20 unique indices from the 64 options
    indices = np.random.choice(64, 20, replace=False)
    # replace the selected elements of the 0's matrix with 1's
    np.put(matrix, indices, 1)
    return matrix

In [34]:
mat = [[1, 1, 0],
       [1, 1, 0],
       [0, 0, 1]]
N = len(mat[0])
used = [False] * N
v = permRecurse(0, used, mat)
print(v)

2


In [35]:
matrix = generate_matrix()
print(matrix)

[[0 1 0 0 1 0 0 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 1 1]
 [1 0 1 0 1 0 0 1]
 [0 0 0 0 0 0 0 0]
 [1 0 1 1 1 0 0 0]]


In [36]:
N = len(matrix[0])
used = [False] * N
v = permRecurse(0, used, matrix)
print(v)

0


In [37]:
def calculate_max_perm(trials):
  permanents = []
  for i in range(trials):
    matrix = generate_matrix()
    N = len(matrix[0])
    used = [False] * N
    v = permRecurse(0, used, matrix)
    permanents.append(v)
  return max(permanents)


In [38]:
calculate_max_perm(100000)

17